language: go
sudo: false
go:
  - "1.11"
  - "1.10"
  - "1.9"
  - "1.7"
  - "1.8"
  - master
before_install:
  - go get github.com/mattn/goveralls
script:
  - $HOME/gopath/bin/goveralls -service=travis-ci

